when:
  - event: push
    branch: main

steps:
  - name: gitleaks
    image: ghcr.io/gitleaks/gitleaks:latest
    commands:
      - gitleaks detect --source . --redact -v

  - name: build-and-push
    image: quay.io/buildah/stable
    privileged: true
    backend_options:
      kubernetes:
        securityContext:
          privileged: true
    environment:
      STORAGE_DRIVER: vfs
    commands:
      - export TAG=${CI_COMMIT_SHA:0:12}
      - export REG=192.168.0.202:5000
      - buildah bud -f docker/Dockerfile.dev -t $REG/isochrone-app:$TAG .
      - buildah push --tls-verify=false $REG/isochrone-app:$TAG

  - name: trivy-scan
    image: aquasec/trivy:latest
    commands:
      - export TAG=${CI_COMMIT_SHA:0:12}
      - export REG=192.168.0.202:5000
      - trivy image --insecure --exit-code 0 --severity HIGH,CRITICAL --ignore-unfixed $REG/isochrone-app:$TAG

  - name: test-unit
    image: 192.168.0.202:5000/isochrone-app:${CI_COMMIT_SHA:0:12}
    commands:
      - python manage.py test
          myapp.tests.test_db_logic
          myapp.tests.test_cleanup_commands
          -v 2

  - name: test-osm
    image: 192.168.0.202:5000/isochrone-app:${CI_COMMIT_SHA:0:12}
    commands:
      - python manage.py test
          myapp.tests.test_full_integration.OsmGenerationTest
          -v 2

  - name: update-gitops-tag
    image: alpine:latest
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache git yq
      - export TAG=${CI_COMMIT_SHA:0:12}

      - git clone https://$GITHUB_TOKEN@github.com/Yibbzz/homelab-gitops.git /tmp/gitops

      - cd /tmp/gitops/homelab-gitops

      - yq -i ".image.tag = \"$TAG\"" apps/isochrone/dev.yaml

      - git config user.email "woodpecker@ci"
      - git config user.name "Woodpecker CI"

      - git add apps/isochrone/dev.yaml
      - git commit -m "chore: deploy isochrone $TAG [skip ci]"
      - git push origin main