AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating a CodePipeline for a Django app.
  
Parameters:
  ArtifactStoreS3BucketName:
    Type: String
    Description: Name of the S3 bucket for storing pipeline artifacts
    Default: my-pipeline-artifacts-2

  CodeStarConnectionArn:
    Type: String
    Description: ARN of the CodeStar connection
    Default: arn:aws:codestar-connections:eu-north-1:992382406887:connection/a1d513a0-f84a-4b17-9249-33d940f6c782

  FullRepositoryId:
    Type: String
    Description: Full repository ID (owner/repo)
    Default: Yibbzz/webapp

  BranchName:
    Type: String
    Description: Branch name
    Default: main

Resources:
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCodePipelineServiceRole-eu-north-1-main-2
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Path: /service-role/

  CodeBuildEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for CodeBuild encryption
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCodeBuildEncryption
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

                
  DjangoAppECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: django-app
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: false
      EncryptionConfiguration:
        EncryptionType: AES256

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codebuild-django-aws-project-service-role
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
      Policies:
        - PolicyName: ecr-perms
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ECRPermissions
                Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:GetAuthorizationToken
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                Resource: '*'
      ManagedPolicyArns:
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/service-role/CodeBuildImageRepositoryPolicy-django-aws-project-eu-north-1'  
  
  ArtifactStoreS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArtifactStoreS3BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ArtifactStoreS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactStoreS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${ArtifactStoreS3Bucket}'
              - !Sub 'arn:aws:s3:::${ArtifactStoreS3Bucket}/*'

  DjangoAppCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: django-app
      Description: CodeBuild project for Django application.
      Source:
        Type: GITHUB
        Location: https://github.com/Yibbzz/webapp.git
        GitCloneDepth: 1
        GitSubmodulesConfig:
          FetchSubmodules: false
        BuildSpec: aws-buildspec.yml
        ReportBuildStatus: false
        InsecureSsl: false
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: NO_CACHE
      Environment:
        Type: ARM_CONTAINER
        Image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables: []
        PrivilegedMode: false
        ImagePullCredentialsType: CODEBUILD
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !GetAtt CodeBuildEncryptionKey.Arn
      LogsConfig:
        CloudWatchLogs:
          Status: DISABLED
        S3Logs:
          Status: DISABLED
          EncryptionDisabled: false
      Visibility: PRIVATE

Outputs:
  RoleARN:
    Description: ARN of the CodeBuild Role
    Value: !GetAtt CodeBuildServiceRole.Arn