apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: {{ include "isochrone.ns" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-secret-reader
  namespace: {{ include "isochrone.ns" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["postgres-secret"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-secret-binding
  namespace: {{ include "isochrone.ns" . }}
subjects:
  - kind: ServiceAccount
    name: postgres-sa
    namespace: {{ include "isochrone.ns" . }}
roleRef:
  kind: Role
  name: postgres-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ include "isochrone.ns" . }}
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres-sa
      securityContext:
        fsGroup: 1000
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: RUN_AS_ROOT
              value: "false"
            - name: POSTGRES_UID
              value: "1000"
            - name: POSTGRES_GID
              value: "1000"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ include "isochrone.ns" . }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
