apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.className }}
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ include "isochrone.ns" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.postgresSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim   # named to comply with the graphhopper creation
  namespace: {{ include "isochrone.ns" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.efsClaimSize }}
