apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-django-app
  template:
    metadata:
      labels:
        app: my-django-app
    spec:
      serviceAccountName: django-app-service-account
      initContainers:
      - name: init-webapp
        image: 992382406887.dkr.ecr.eu-north-1.amazonaws.com/django-app:latest
        imagePullPolicy: Always
        command: ['/bin/sh', '-c', 'cp -r /webapp/media/user_osm_files/* /mnt/ && echo Files copied']
        volumeMounts:
        - name: osm-volume
          mountPath: /mnt
      containers:
      - name: my-django-app
        image: my-django-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: osm-volume
          mountPath: webapp/media/user_osm_files
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: my-db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-db-secret
                key: password
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: my-db-config
                key: name
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: my-db-config
                key: host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: my-db-config
                key: port
      volumes:
      - name: osm-volume
        persistentVolumeClaim:
          claimName: shared-osm-files
