apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-django-app
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-north-1:992382406887:certificate/43ec92fd-3c1c-4da7-a1a4-2ef0418f10b2
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-django-service  # Corrected service name
            port:
              number: 80  # The port that your service is listening on
---
apiVersion: v1
kind: Service
metadata:
  name: my-django-service
spec:
  type: ClusterIP
  selector:
    app: my-django-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: django-app-service-account
