apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: 992382406887.dkr.ecr.eu-north-1.amazonaws.com/django-app:latest
        imagePullPolicy: Always
        command: ["celery", "-A", "webproject", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: my-rds-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-rds-secret
                key: password
          - name: DB_NAME
            value: "postgresdb" 
          - name: DB_HOST
            value: "database-1.c9q0imsss307.eu-north-1.rds.amazonaws.com"
          - name: DB_PORT
            value: "5432"