apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-django-app
  template:
    metadata:
      labels:
        app: my-django-app
    spec:
      serviceAccountName: django-app-service-account
      initContainers:
      - name: init-webapp
        image: 992382406887.dkr.ecr.eu-north-1.amazonaws.com/django-app:latest
        imagePullPolicy: Always
        command: ['sh', '-c', 'cp -r /webapp/media/user_osm_files/* /mnt/ && echo Files copied']
        volumeMounts:
        - name: osm-volume
          mountPath: /mnt
      - name: migrate
        image: 992382406887.dkr.ecr.eu-north-1.amazonaws.com/django-app:latest
        imagePullPolicy: Always
        command: ['sh', '-c', 'python manage.py makemigrations && python manage.py migrate']
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-rds-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-rds-secret
              key: password
        - name: DB_NAME
          value: "postgresdb"
        - name: DB_HOST
          value: "database-1.c9q0imsss307.eu-north-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
      containers:
      - name: my-django-app
        image: 992382406887.dkr.ecr.eu-north-1.amazonaws.com/django-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: osm-volume
          mountPath: webapp/media/user_osm_files
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-rds-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-rds-secret
              key: password
        - name: DB_NAME
          value: "postgresdb"
        - name: DB_HOST
          value: "database-1.c9q0imsss307.eu-north-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
      volumes:
      - name: osm-volume
        persistentVolumeClaim:
          claimName: efs-claim
