# Generated by Django 5.0 on 2023-12-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='motorway',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='path',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='residential',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='mph',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='selection',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
