# Generated by Django 5.0 on 2024-01-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_isochrone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='selection',
            field=models.CharField(choices=[('motorway', 'Motorway'), ('residential', 'Residential'), ('path', 'Path')], max_length=50),
        ),
    ]
