# Generated by Django 5.0 on 2024-01-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_userpreferences_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isochronepreferences',
            name='buckets',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='isochronepreferences',
            name='mode_selection',
            field=models.CharField(default='Car', max_length=10),
        ),
        migrations.AlterField(
            model_name='isochronepreferences',
            name='time_limit',
            field=models.IntegerField(default=10),
        ),
    ]
