# Generated by Django 5.0 on 2024-01-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_isochronepreferences_buckets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userport',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
