# Generated by Django 5.0 on 2024-01-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_userport_is_running'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userport',
            old_name='port',
            new_name='port1',
        ),
        migrations.AddField(
            model_name='userport',
            name='port2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
