# Generated by Django 5.0 on 2024-01-06 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_userport_container_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPreferences',
            new_name='NetworkType',
        ),
    ]
