# Generated by Django 5.0 on 2024-01-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_userpreferences_networktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userport',
            name='button_activate',
            field=models.BooleanField(default=False),
        ),
    ]
