# Generated by Django 5.0 on 2024-01-13 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_userport_button_activate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrawnGeometry',
            new_name='BoxGeometry',
        ),
    ]
