# Generated by Django 5.0 on 2024-02-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_usersessionstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isochronepreferences',
            name='mode_selection',
            field=models.CharField(default='walk', max_length=10),
        ),
    ]
