# Generated by Django 5.0 on 2024-02-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_isochronepreferences_mode_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isochronepreferences',
            name='mode_selection',
            field=models.CharField(default='foot', max_length=10),
        ),
    ]
