# Generated by Django 5.0 on 2024-02-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_isochronepreferences_mode_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networktype',
            name='mph',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
