# Generated by Django 5.0 on 2024-02-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_networktype_mph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userport',
            old_name='container_name',
            new_name='pod_name',
        ),
    ]
