# Generated by Django 5.0 on 2024-02-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_container_name_userport_pod_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userport',
            name='is_running',
        ),
    ]
