---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: kube-system
spec:
  encryptedData:
    tunnel.json: AgCvTOFRqHaCSEoluF5ARCWyg0u/1lc8Zi4vm3rTe/2NiQV7Li9FPP5Hg3oMoVV+u13QDVMLkGVA3BbfcSJVsWNu4Ma5vFJaadQn1Ach1YYwuQEEMTPfYydLg8DErKw81HG7pspoYa+y3AzF1O7skvf02jrzIt1NSLf7f3yaBAA07sWsJ9hdj+yaCixpEhPkncJjI14fYbFsjpUVSuTg52J9uKPu7soQvfuEauu7gOu8DST7ljMQAjNWo9X7zasq+Ut2oDu/jgDqjlIkLHs9afBYeW1PDQJGeB7dkwU53ubByhet2Y63IqM9ie+idO0uULtTkbWCxwNtGIPdT5/fpPfpw866QZX43W2Oc46oRPZoe4nlwtVmWc4YzIqlONfRUWoQ6knkEduUDU/agRkDevEBHMU5AQiwgQvFOl5vXjf714r2WNIpHgrW8d4ajQHeSdE6nR5Y88JGuGZmQOqKd2nGRcgGtzdw+n+Bwq41qhDEIIh/tKZplxRjZDQZ21+F3KoIHOS/N8XLBjUS7FM6hFcMlP1uqdwHWr4ap0N0ETxV0Bd25oTlNUfttdWSPd7IBOu4Kswxd8H4Qvo/wWjaDb4FdpWLRZULy9gfZQQDI6ZWa75W1BYREvmXfKLn2xWtTGOi3pBcAjRfvtcfVaL03f4sMRZ9oOMAmnSd8zyuxXGYaq0GJWO+GaxbtOysEwZ03Dqj43vpaO7JnM7+q/wvlccTZZflEDKvYSj7HR42j4cisVLgMSgoQaiBlUoW7MNVZSub2YEcEGpEK4PuKVVry1jIoYJJAFCf06Jv/g1MQKTk4+tBfP5SLcC96mt6jc7RpvD8cCwhz+nT3WQ3gyPQzhaqECxY1t1OFPHgaUp82V3xrVbn60F30ki2yhcou/+e9ryw3siDGB8TtUO3H7o5wc4KWEQfRNm0KcfrFxGKk+KuiMKsWevbi2vcseEV6qr9qetu
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: kube-system
    type: Opaque
